### ISSUE TITLE
please look at my comment in the README.rst

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#1]
a good intro for someone who does not know the goal of the project is still missing

**Comment by shreyanshk** [comment]
I have updated the README.rst file.
Please consider providing feedback.

**Comment by atrent** [comment]
Still no sign of a summary of the usecases, please put yourself in your would-be user's shoes, he's coming to your project and tries to understand what to do in various cases/contexts, e.g.:

- I already have a router that gives addresses via DHCP and it's not capable of TFTP-ing
- I have a pc that can do DHCP+TFTP (i.e., I am root) but the net in which I am is managed by an external DHCP
- I'm on a server that can do DHCP+TFTP and is the DHCP server (using dnsmasq) of this net, what happens to my dnsmasq original configuration?
- I have a mix of 32/64 bit machines to be booted, what I can do?
- The server must be 32 or 64 bits?
- et cetera

Use diagrams, schemas, etc. to explain yourself, try to imagine every conceivable problem the user may experience.

This is a "complex" setup (many machines involved, with different roles/architectures/etc.) and the complexity should be forecast and described.

**Comment by shreyanshk** [comment]
I've added some use case summary at the introduction: https://boottorrent.readthedocs.io/en/latest/index.html
I've tried to answer most of the questions at the faq: https://boottorrent.readthedocs.io/en/latest/faq.html

**Comment by atrent** [comment]
(commented the README file)

**Comment by shreyanshk** [comment]
Intro, FAQs and setup diagrams are there now.
Let me know if there are any issues.

**Comment by atrent** [comment]
search for (atrent) comments in the files

**Comment by shreyanshk** [comment]
Took care of all the comments.
Please comment on the commits.
