### ISSUE TITLE
requirements in the README file

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#11]
these requirements are for the server only, correct?
and not even all of them if the bootimage is already created?
it may be useful to distinguish the requirements for every phase

**Comment by shreyanshk** [comment]
Yes! makes sense.
I've added it.

**Comment by atrent** [comment]
very briefly indeed... you should be more detailed

**Comment by shreyanshk** [comment]
Fixed in 97c740d218c7dd430c2a225f20d8046a363d77f7
