### ISSUE TITLE
system architecture description is badly needed

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#12]
you should describe (maybe with a diagram) the various components of the system you're thinking and working on, with a "map" (a matrix) of "what should run on which component"

**Comment by gbiscuolo** [comment]
Hi Shreyanshk,

* atrent [2018-06-10 06:14:37 -0700]:

>you should describe (maybe with a diagram) the various components of the
>system you're thinking and working on, with a "map" (a matrix) of "what
>should run on which component"

please consider this a priority for the next few days, it's more important
than adding new features to the code (at this project stage)

as mentors you will make a lot easier for us to always have the general idea
about the project no matter what specific inplementation you'll use

you can start with a simple nested list of involved components, then - as
suggested by Andrea - you could try creating a simple diagram, e.g.
http://sl-lab.it/dokuwiki/doku.php/tesi:boottorrent_en#test_configuration
(the double 1GBps network switch on the right sould be simplified and
replaced by one only, IMHO)

please add to the diagram the software components needed on each machine and
the interactions with other components

please consider that with sphinx-doc is possible to create variuos kind of
diagrams via several extensions like python3-sphinxcontrib.plantuml (various
UML diagrams), python3-sphinxcontrib.nwdiag (network diagrams) and the
family of python3-sphinxcontrib.*diag extensions (http://blockdiag.com/en/)

ciao
Giovanni

-- 
Giovanni Biscuolo
Xelera - IT infrastructures
http://xelera.eu/contact-us/

**per favore** Quota Bene: http://wiki.news.nic.it/QuotarBene
**please** use Inline Reply: https://en.wikipedia.org/wiki/Posting_style#Interleaved_style

**Comment by shreyanshk** [comment]
Hope this is what you are looking for: https://boottorrent.readthedocs.io/en/latest/internals.html

**Comment by atrent** [comment]
the sequence diagram of the TUI is useless without explanation of every component/instance, names are not very self-explanatory

the small resolution does not help

if you want to use UML (which I like!) you should start with class[*] diagram


[*] where classes are at a high abstraction level, not actual implementation classes!

**Comment by shreyanshk** [comment]
I've done some research on the internet on how to write "architectural introductory overview" and written some documentation here at: Architecture document page and internals page
https://boottorrent.readthedocs.io/en/latest/architecture.html
https://boottorrent.readthedocs.io/en/latest/internals.html
I've also added some more documentation on the the process here:
https://boottorrent.readthedocs.io/en/latest/internals.html#interactions-at-a-glance

Please provide feedback.

**Comment by atrent** [comment]
(commented the architecture file)
