### ISSUE TITLE
python version concerns

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#14]
I'm concerned about your choice of python 3.6, it's a version that's not available on Debian stable (in fact it's only in testing and unstable), many servers use stable...
Can you motivate?

Maybe the virtualenv tool is able to download an entirely new and recent version of python?

**Comment by gbiscuolo** [comment]
I think this is not a big issue since it's likely that a boottorrent Debian package (next step) will be accepted only in sid at first and eventually in buster *only* before it will be freezed (see https://release.debian.org/#release-dates)

**Comment by shreyanshk** [comment]
f-strings !!
I started out with:

>>> name = "shreyansh"
>>> "Hello, " + name + "!"
"Hello, shreyansh!"

Then:
>>> "Hello, {person}!".format(person=name)
And:
>>> "Hello, %s!" % name

But nothing beats the simplicity and readability of f-strings.

>>> f"Hello, {name}!"

Now, such string substitutions are being done multiple times in this project. This project is an ideal use case of f-strings. They improves both readability and conciseness of the code. Also, they are much less of burden on my sanity (w.r.t pesky concatenations).
They were introduced with the release of Python 3.6

Please close the issue if you're satisfied.

**Comment by shreyanshk** [comment]
Closing issue since it was decided that there is no need to refactor.
