### ISSUE TITLE
maybe a missing dependency?

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#16]
I'm trying boottorrent  on a clean Debian (Devuan actually) machine, after cloning and 'make initrd' I tried:

$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

Then by installing python3-setuptools it (almost) works since the command should be prepended with sudo?

**Comment by shreyanshk** [comment]
I'll add a note in the installation section.

Setuptools is the de facto package development library in Python and is implicitly installed Python installers.
I mean, even if I were to add setuptools as dependency, without it's presence on the system, Python wouldn't know how to parse dependencies for anything. You'll still be in the same spot. Sorry about that.

**Comment by shreyanshk** [comment]
Added note in 0f02fe408f7f2849750fd8140bcf4fec419ae115

**Comment by atrent** [comment]
should it be listed in the dependencies?

**Comment by atrent** [comment]
ok as for now, we'll come back on the dependencies topic when facing the packaging phase

**Comment by shreyanshk** [comment]
Debian packaging is taking care of the dependencies, so closing this issue.
