### ISSUE TITLE
yet another install error

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#17]
$ sudo python3 setup.py install
[sudo] password for bt: 
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    readme = readme_file.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 728: ordinal not in range(128)

**Comment by shreyanshk** [comment]
Are you using non UTF-8 or ASCII locale?

I happen to accidentally slip (commit b3a23abd6aa8d3d493c6768b2100c299ca33b649) in UTF-8 characters in ASCII based README.rst file.
I was editing the file in Libreoffice Writer and didn't knew that its apostrophes were Unicode code point 8217 & 8216 rather than standard ASCII/Unicode code point 39.

So, python's locale detection failed.
I'm wiser now and I've fixed it.

**Comment by atrent** [comment]
$ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE=en_GB.UTF-8
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE=en_GB.UTF-8
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES=en_GB.UTF-8
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=it_IT.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=

**Comment by shreyanshk** [comment]
Please consider retrying.

**Comment by atrent** [comment]
it works now (git pulled and re-executed install), but I had to set:

$ export LC_ALL=C.UTF-8
$ export LANG=C.UTF-8

to avoid:

`Traceback (most recent call last):
  File "/usr/local/bin/boottorrent", line 11, in <module>
    load_entry_point('boottorrent==0.1.0', 'console_scripts', 'boottorrent')()
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
`

**Comment by shreyanshk** [comment]
With this commit, the code is modified to read the files in utf-8 encoding (or whatever encoding the files were written, which happens to be utf-8 here). The user can have any encoding, it won't matter. This change won't throw an error if any other encoding other than utf-8 is used.
