### ISSUE TITLE
sequence diagram

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#19]
in the https://boottorrent.readthedocs.io/en/latest/internals.html doc page, the sequence diagram is not very readable, if (as suggested) I open it in a new page this is the result:
![seqdiag-971af0c337bafa98241ac8f460a9a2030d34b89d png 1216x742 - chromium_120](https://user-images.githubusercontent.com/412584/41506665-70c0ae24-7222-11e8-96d4-44a8102b8b37.png)

**Comment by atrent** [comment]
yes, good

**Comment by shreyanshk** [comment]
Fixed it 509a0ae0fadbd44d24c5c1bc6d03f50195effd12
Please clear your browser cache in case you're still seeing old version.
