### ISSUE TITLE
starting boottorrent and netcard config

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#22]
when starting boottorrent the network card should be already configured statically otherwise dnsmasq could fail

**Comment by shreyanshk** [comment]
I've added a note (ad48b75196ad2410ed9a3c45c7e2d956c0b08ef5).
Please mark the issue closed if the commit is okay.

**Comment by atrent** [comment]
I commented the commit, add a small note and then close this issue

**Comment by shreyanshk** [comment]
(0046a2d3911faae137c0f8c4ab99f5409a6868c6)
