### ISSUE TITLE
transmission daemon should be inactive

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#23]
or the boottorrent-activated transmission daemon (I'm referring to the /etc/init.d/... one) should work on a different port
(maybe a note in the doc?)

**Comment by atrent** [comment]
at least list the possible conflicting (dns, bootp, tftp, torrent, etc.) ports!

**Comment by shreyanshk** [comment]
I've added a note (0046a2d3911faae137c0f8c4ab99f5409a6868c6) in the configuration section.
