### ISSUE TITLE
could not contact transmission

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#24]
on the booting node, see:
![2018-06-23 14 51 24](https://user-images.githubusercontent.com/412584/41809886-49f5a312-76f5-11e8-8cfd-fa7cb12038ff.jpg)

**Comment by shreyanshk** [comment]
As referenced in #21, you have enabled Hefur as external tracker. Can you verify a process named "hefurd" is running in the background?
Aria2 is trying to connect to this torrent tracker to discover peers but It is unable to do so.
Here's Hefur's link: https://github.com/abique/hefur

**Comment by shreyanshk** [comment]
> man pages for all commands and config files needed
A README.rst file is there in BootTorrent env, if it was generated using ``boottorrent`` executable. Wouldn't it suffice?

> and fully commented config files also
It was previously commented but I moved that information to README.rst file (referenced above) to make config file look cleaner and separate concerns of various files.

**Comment by atrent** [comment]
in a future Debian package a man page would be a must (I believe)
now I've found the READMEs:
$ find -name 'READM*'
./phase1bootstrap/slitaz/README.rst
./README.rst
./boottorrent/assets/README.rst
./boottorrent/assets/skel/oss/README.rst
./boottorrent/assets/skel/README.rst

are they referenced in the documentation?

**Comment by shreyanshk** [comment]
> are they referenced in the documentation?

Yes!

**Comment by atrent** [comment]
when you answer to a question, in general, please be more detailed, "yes"... where?

**Comment by shreyanshk** [comment]
Oh! sorry. The links are: https://boottorrent.readthedocs.io/en/latest/usage.html#configuring-boottorrent and https://boottorrent.readthedocs.io/en/latest/usage.html#adding-operating-systems for (/boottorrent/assets/skel/README.rst) and (/boottorrent/assets/skel/oss/README.rst).

(/phase1bootstrap/slitaz/README.rst) and (/boottorrent/assets/README.rst) are simple lists of the files contained. So, are not included in the docs currently.

README.rst is at https://boottorrent.readthedocs.io/en/latest/index.html#
