### ISSUE TITLE
verbose autodiscovery ?

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#25]
I'm running boottorent without hefur, it's taking ages... can the autodiscovery be made more verbose?

**Comment by shreyanshk** [comment]
> can the autodiscovery be made more verbose

Do you mean to say more 'faster'?

**Comment by atrent** [comment]
no, more verbose, to see what's going on in the search

**Comment by shreyanshk** [comment]
Yes! It can be made more verbose. The code is not there as of now, though.
