### ISSUE TITLE
hefur is not a standard package (Debian/Devuan at least)

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#26]
are there alternatives?

**Comment by shreyanshk** [comment]
Yes! they are listed in the docs: https://boottorrent.readthedocs.io/en/latest/internals.html#hefur
But none of these packages belong to Debian's repo as a standard package.

**Comment by atrent** [comment]
and all this is to avoid having a small http server running?

**Comment by shreyanshk** [comment]
No! It is not because of that.
As referenced in #25, the reason it is taking ages is because decentralized peer discovery technologies (DHT and LPD) are slow.

Problem with DHT:
DHT requires connection to global network on the internet (AFAIK, I know)
A DHT client needs IP:PORT of at least one other DHT enabled client (who itself has to be connected to the global network)
Due to above need and dynamic nature of torrent networks, it is not possible to distribute a DHT seed file with BootTorrent, as it will become stale just in few days.
So, DHT is not ideal.

Problem with LPD:
Depends on network broadcasting and due to the nature of it, a client broadcasts it's torrents periodically on the order of 10s of minutes. The long time is to avoid Broadcast Storm/Radiation (https://en.wikipedia.org/wiki/Broadcast_radiation) cases. That is why it's taking so much time in #25 because it's stuck on waiting to discover peers via LPD.

That is why an external tracker is used. Hence, hefur.

**Comment by atrent** [comment]
- DHT: remove it, I realized only now that you were referring to distributed hashtables, remember that is very likely that this project will be used while NOT connected to the internet!
- I'll try with LPD
- we need a more practical solution, the original project just used a configurable IP as a tracker, why not doing the same?

BTW can symbolic names be used instead of IPs?

**Comment by shreyanshk** [comment]
> DHT: remove it

> we need a more practical solution, the original project just used a configurable IP as a tracker, why not doing the same?

The tracker IP is configurable but it's using a private tracker.
We have to consider that public trackers are sometimes indexed by torrent search websites and not everybody would be comfortable with their BootTorrent OSs being indexed on the internet. (same problem with DHT)
Also, a public tracker will be unreachable if there is not Internet. (same problems with DHT).
So, a private tracker is used on the host and it's IP is sent to clients when clients request their configuration.

**Comment by atrent** [comment]
the tracker in the original project was private, no need of Internet at all

am I missing something?

**Comment by atrent** [comment]
bittornado?

**Comment by shreyanshk** [comment]
Sir, it's last release was like 11 years ago.
And, it's a bittorrent client, not bittorrent tracker.
It doesn't provide the function the project needs.

**Comment by atrent** [comment]
it's described as "bittorrent client (and tracker) with console and curses interfaces", if it still works...

**Comment by shreyanshk** [comment]
It is written in Python 2.
Python 2 is currently being phased out from everywhere. Distributions are pushing to have their dependencies in Python 3 and removing Python 2 versions.

I'd suggest not to switch to bittornado at least.

**Comment by atrent** [comment]
ok

but I'd leave this issue open for further analysis

**Comment by atrent** [comment]
DHT: of course, just disable it by default, I think it won't be used often

**Comment by atrent** [comment]
did you go through this list?
https://en.wikipedia.org/wiki/Comparison_of_BitTorrent_tracker_software

**Comment by atrent** [comment]
given the problems and dependencies in building hefur I'd recommend choosing a simpler product

**Comment by atrent** [comment]
https://erdgeist.org/arts/software/opentracker/#build-instructions
e.g., this one, I built it in 30 sec, only libowfat-dev as a dependency

**Comment by atrent** [comment]
`git clone https://github.com/abique/hefur.git
cd hefur
git checkout 0.6
git submodule init
git submodule update
sed -i "s/PROJECT_NUMBER.*/PROJECT_NUMBER=0.6/g" Doxyfile
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
file hefur/hefurd
>>> hefur/hefurd: ELF 64-bit LSB pie executable x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=c6b511da923c11920b15f436bb330072bdda27e3, not stripped`

where did you find these instructions?

**Comment by shreyanshk** [comment]
> e.g., this one, I built it in 30 sec, only libowfat-dev as a dependency

I've listed this in alternatives. It's not a standard debian package and also requires processing a config file. But It's possible to replace Hefur with this.

> where did you find these instructions?

Generic instructions are in the manual (line 50:70): https://github.com/abique/hefur/blob/master/manual/manual.xml
I used ``git clone https://github.com/abique/hefur.git && git submodule init && git submodule update`` to download the project and then proceeded according to the manual.
``sed -i "s/PROJECT_NUMBER.*/PROJECT_NUMBER=0.6/g" Doxyfile`` is used to set version number. ``cmake -DCMAKE_INSTALL_PREFIX=/usr ..`` is used to set install prefix of the final file.

**Comment by atrent** [comment]
- hefur, you have to admit that they did not do anything to help in finding these instructions
- opentrack, I know it's not packaged, but it's very small and it builds in seconds (it is lacking the web interface, but I did not see mention of the web interface in the boottorrent user doc)

**Comment by atrent** [comment]
hefur build: needs libarchive-dev, libgnutls-dev and cmake
and it still gives error on mimosa (google/protobuf/compiler/code_generator.h not found)

**Comment by atrent** [comment]
hefer build (continued): mimosa should be cmake+make(ed) ? I'm trying... discovered that mimosa depends on liblzma.dev, libbison-dev and flex (!!!) and still does NOT compile

**Comment by atrent** [comment]
I'm giving up on hefur, sorry

**Comment by shreyanshk** [comment]
> hefur, you have to admit that they did not do anything to help in finding these instructions

I mean there's a manual folder. I happen to check it beforehand when I was vetting it.

> opentrack, I know it's not packaged, but it's very small and it builds in seconds

I mean, I tried building opentracker.
Then, it required libowfat, which requires dietlibc and so on...
I can replace it with opentracker as you suggest.

**Comment by atrent** [comment]
libowfat-dev depends on libc6-dev and libowfat0

**Comment by shreyanshk** [comment]
> why not giving the configurable option of launching any tracker?

It is possible to accommodate any tracker by moving the responsibility of the tracker to the user by adding an option to list urls of trackers. But, then, if so many components are already being handled by BootTorrent, it makes sense (to me) to add other component (which, by the way, is crucial to the process) too.

Do you suggest to move the tracker process out of BootTorrent?

**Comment by atrent** [comment]
I understand the need to pack everything into boottorrent, but if the build is so troubled...
Try to think about a Debian/Devuan boottorrent package, how would you pack hefur into it?

I'm not suggesting to move out, just to think about it (let's reason on the mailing list)

**Comment by shreyanshk** [comment]
I understand your requirements and please know that it was close competition between opentracker and hefur. I understand that it's possible that the attributes you weight may be different than what I weight.

I can swap hefur with opentracker. I mean, I don't have any issues with it. I just want a tracker to help the user into the process.

**Comment by atrent** [comment]
I just tried: running opentracker (-p 10001) before launching 'boottorrent start' (leaving hefur enabled in yaml on 10001 but not having the actual hefur installed) WORKS smoothly

and the binary is 80k

and it has a minimal web interface for stats

:)

**Comment by atrent** [comment]
I think it would be better to let the user choose

Please, try to describe the packaging process... well, it's the next step ;)

**Comment by shreyanshk** [comment]
Hefur replaced with OpenTracker, Closing issue.
