### ISSUE TITLE
timeout should be visible

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#27]
if boot timeout is enabled a "countdown timer" should be visible in the TUI

**Comment by shreyanshk** [comment]
A 'countdown timer' is visible. Unless it is disabled, of course.
Are you on the recent version of BootTorrent? I pushed this update today.

**Comment by atrent** [comment]
no sign of countdown, I even re-made the ph1 assets...
can you post a screenshot?

**Comment by shreyanshk** [comment]
![screenshot_20180623_225211](https://user-images.githubusercontent.com/8820721/41812005-23944992-7738-11e8-8f2b-5602786ef659.png)

Please check the VirtualBox window.

**Comment by shreyanshk** [comment]
``"ctrl-c" at the bottom`` that means it's an old version.
Can you use ``git log`` to check if this commit is there? (https://github.com/shreyanshk/boottorrent/commit/84b1a02d2fc963d80e8ebbfd0a9b953397b5f2a3)

I am checking this commit as we speak and I have pushed a new binary file.

**Comment by atrent** [comment]
I have the commit but still no timer, should I recreate something special?

**Comment by shreyanshk** [comment]
> I have the commit but still no timer, should I recreate something special?

No, you shouldn't have to.

Try this:
Remove previous installation ``pip uninstall boottorrent`` and then install from new sources. (use sudo or virtualenv if you've previously used that to install)

**Comment by atrent** [comment]
relaunching 'python3 setup.py install' (how I originally installed) recreated everything and now at least it boots with the timer

please add a warning in the doc

**Comment by shreyanshk** [comment]
I've added instructions (70630c1a006b79e1eb54b49ea080b909bcba31a6). Is it better?

Also, I suggest you to stop using 'python setup.py install'. Please look at updated install instructions in the guide.

**Comment by atrent** [comment]
I'll do a clean install
