### ISSUE TITLE
tmux/screen?

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#28]
in the phase1 boot could it be useful to have a tmux/screen session opened to have a shell in parallel with the boottorrent procedure?

**Comment by shreyanshk** [comment]
It might be useful but I can only consider it after I've fixed all these issues....
This is going to take some time.

**Comment by atrent** [comment]
then just leave it open

**Comment by gbiscuolo** [comment]
* atrent [2018-06-23 10:03:35 -0700]:

>in the phase1 boot could it be useful to have a tmux/screen session opened
>to have a shell in parallel with the boottorrent procedure?

no, please don't add useless deps

with agetty it's trivial to have two consoles on the client machine and
switch to them using CTRL-ALT-<console> :-)

please refer to https://wiki.debian.org/getty

Ciao
Giovanni

-- 
Giovanni Biscuolo
Xelera - IT infrastructures
http://xelera.eu/contact-us/

**per favore** Quota Bene: http://wiki.news.nic.it/QuotarBene
**please** use Inline Reply: https://en.wikipedia.org/wiki/Posting_style#Interleaved_style

**Comment by atrent** [comment]
yes, you're right, I did not think about it, sorry
