### ISSUE TITLE
error in "make initrd"

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#3]
$ make initrd
tui.go:5:2: cannot find package "github.com/jroimartin/gocui" in any of:
	/usr/lib/go-1.10/src/github.com/jroimartin/gocui (from $GOROOT)
	/home/.../apps/GOPATH/src/github.com/jroimartin/gocui (from $GOPATH)
tui.go:6:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/lib/go-1.10/src/gopkg.in/yaml.v2 (from $GOROOT)
	/home/.../apps/GOPATH/src/gopkg.in/yaml.v2 (from $GOPATH)
make: *** [Makefile:4: initrd] Error 1

**Comment by atrent** [comment]
of course you need to:
$ go get github.com/jroimartin/gocui
and
$ go get gopkg.in/yaml.v2
but it should be stated in the doc

**Comment by shreyanshk** [comment]
I've fixed it.
Thank you.

**Comment by atrent** [comment]
when you "fix" something, please provide a link (where applicable) to the file(s) you changed

**Comment by shreyanshk** [comment]
I referenced the commit (c28a8ddbaa379123e5d54af1b291f34831fb053c) when I closed the issue.
Please check above the "I fixed it" comment.

**Comment by atrent** [comment]
didn't notice, sorry, that's fine

**Comment by atrent** [comment]
maybe you should offer a target in Makefile offering to 'go get' the needed packages

**Comment by shreyanshk** [comment]
Done
https://github.com/shreyanshk/boottorrent/commit/f3d9da6b18d7be94bfb790e67bc3b9943e72e41a
