### ISSUE TITLE
qemu-iso method not starting

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#30]
I'm testing the iso boot without success, after the torrent is finished a single underscore cursor is displayed and nothing happens, could it be that when using qemu-iso method I've seen in tui.go that you launch
`qemu := exec.Command("/usr/bin/qemu-system-x86_64")`
but this may not work on 32bit machines?

also, what are the qemu memory parameters? qemu defaults to 128M

**Comment by atrent** [comment]
(apropos memory parameters) I've seen that args should be valid also for the qemu-iso method, correct?

**Comment by shreyanshk** [comment]
I'm trying to reproduce it. What image are you trying to run?

> but this may not work on 32bit machines?

Qemu runs in full system emulation mode. So, it emulates full 64-bit machine on 32-bit processors and should work. Though, I've tested it in VirtualBox by disabling 64-bit mode (I have 64-bit processor) and it seems to work, but it may be different with real hardware (as I don't have a 32-bit only hardware).
Hopefully, with more information, I should be able to reproduce it or do something about it.

> what are the qemu memory parameters? qemu defaults to 128M

with ``qemu-iso`` method, currently the default qemu parameters are used (yes, RAM is 128MiB). If complete control is desired, use ``bin-qemu-x86_64`` as it allows passing full parameters to qemu.
It's possible to add a ``memory`` parameter (or any parameter as required) if desired and abstract away Qemu's CLI interface.

> I've seen that args should be valid also for the qemu-iso method, correct?

Currently, args is not a valid parameter with ``qemu-iso`` method. Default values are used. It's possible to add this parameter but that case is already better covered by ``bin-qemu-x86_64`` method, so, I haven't added it.

**Comment by atrent** [comment]
function
`func load_qemu_iso(oskey string)`
and
`func load_bin_qemu_x86_64(oskey string)`
are almost identical (except for the iso part), maybe they could be merged into one and activate iso booting by just managing parameters (args variable) in the yaml?

**Comment by shreyanshk** [comment]
Yes! They are.
It is valid (and currently works by passing "-cdrom isofile" as args) to use ``bin-qemu-x86_64`` to launch any ISO.
The motivation of ``qemu-iso`` was to provide a more straightforward way to boot ISO files and ``qemu-iso`` is just a sub case of ``bin-qemu-x86_64``.

**Comment by atrent** [comment]
booting a ISO with 128M ram is almost impossible except when using very small ISOs, I'm voting for collapsing the two functions into one

**Comment by atrent** [comment]
it seems that qemu-system-x86_64 works also on i386, but I'd test on more environments, I'm putting comments in tui.go

**Comment by shreyanshk** [comment]
7872bbf976b045013942892f7ee48d48520a9332
