### ISSUE TITLE
kvm by default in qemu?

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#31]
would you suggest/put a "-accel kvm" in args for qemu in the various config.yaml?

**Comment by shreyanshk** [comment]
It should be considered that not every machine will have virtualization extensions enabled (unless the user enables it from the BIOS of every machine) or even user configurable.
KVM 'by default' will need to have hardware assisted virtualization 'by default' which is, unfortunately, not the case. (Surely not on consumer grade hardware. Can't talk about enterprise hardware)

**Comment by atrent** [comment]
agreed

if you want put it as commented in examples
