### ISSUE TITLE
qemu launch should be more confgurable?

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#32]
I mean, the actual executable to be launched (whether qemu-system-x86_64 or qemu-system-i386 or any other architecture emu) could be chosen by config.yaml?

**Comment by shreyanshk** [comment]
It's certainly possible but then the executable (and all it's dependencies) in question will have to be included with phase1 linux system. This would increase the image size. IMHO, we are already pushing the image size (it's at ~60MiB as of now).
We must certainly weight the executable against the increased size (small base image size is a core requirement of this project).

I think we can instead have a new method like ``binary`` (or any other name), which will launch an executable included in the torrent.

**Comment by atrent** [comment]
of course this would change the needs for the ph1, but I think that in the long term even the ph1 image will become modifiable by the user

we may also reason about the packages included in the ph1 boot [low pri]

good for the "binary/executable" method, then the responsibility goes to the user that must assure the binary/executable to be present in ph1 image, approved!

**Comment by shreyanshk** [comment]
> we may also reason about the packages included in the ph1 boot [low pri]

I suspect that the base image can be smaller.
But, I haven't had enough time to trim to just essential packages. (Each build takes ~30 minutes and I can't bruteforce my way through remaining 274 packages!)

**Comment by atrent** [comment]
you're right about the image build, I still have to try it!

please open a low pri issue about slimming the slitaz image
