### ISSUE TITLE
Slim SliTaz base image

### ISSUE THREAD

**Issue by shreyanshk** [shreyanshk/boottorrent#33]
Image generation files at ``phase1bootstrap/slitaz``.

**Comment by shreyanshk** [comment]
The current SliTaz base image is generated with default configuration provided by SliTaz devs. The base image currently consists of ~300 packages, many of which are unneeded for BootTorrent.
Since every build requires ~30 minutes, I've alone not had enough time to trim the package list (``distro-packages.list`` file) by trying all possible combinations (270! i.e 270 factorial combinations) of packages in distro-packages.list file.
More man power can be appreciated.

How to do it?

1. Remove some packages from ``distro-packages.list`` file.
2. Build the base image as specified in Guide. (``https://boottorrent.readthedocs.io/en/latest/installation.html#from-sources``)
3. Try to boot node computers and test if all the functions work correctly.
Some of which include: working xorg, qemu, aria2, getty & login on tty2, kexec, xdotool etc.

**Comment by atrent** [comment]
no need to try 270! permutations ;)

start by ordering the list of included packages by decreasing size, then we may discuss the first, say, ten/twenty items

**Comment by shreyanshk** [comment]
Wrote a bit of code to generate sorted list: https://github.com/shreyanshk/boottorrent/blob/dev/phase1bootstrap/slitaz/list
Size in kilobytes.

**Comment by shreyanshk** [comment]
While trying to build the list of packages and their sizes.
I found a way to figure out which file belongs to which package.
(search by file: http://pkgs.slitaz.org/search.sh)

I then proceeded to use the very scientific method of starting from scratch and hammering down the build system till it produces something working while fixing missing file related errors as I go by.

Fixed in 431548c45d37786723582bdc50da06870541ea50

Slimmed the rootfs from 56MB to 28MB. I doubt it can be any slimmer.

**Comment by shreyanshk** [comment]
Lot of extra or rarely used drivers/firmware files were also removed.
I intent to add them only as required.

**Comment by shreyanshk** [comment]
Well, most of those things (dropbear, midori ... etc) were already included in the previous base image before slimming down.
Though, every user can customize their own version with the included build files.

**Comment by atrent** [comment]
exactly

**Comment by shreyanshk** [comment]
I've reverted to previous image.
For reference, this is the list of all the video drivers available in slitaz
http://pkgs.slitaz.org/search.sh?package=xf86-video

**Comment by atrent** [comment]
it works, except for the kvm option

**Comment by atrent** [comment]
KVM: I've found why...

cpus on VX6 (on my client1) and on Samsung R60 (client2) do NOT support kvm!
(no vmx in /proc/cpuinfo flags)

sorry, my fault, I did not notice before
