### ISSUE TITLE
running xorg in ph2 with qemu method: may be made optional?

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#37]
X is not always needed for a qemu method ph2 boot (e.g. when booting OSes such as FreeDOS or a console-mode-only Linux), could it be made optional?

(see also #36)

**Comment by shreyanshk** [comment]
I think it should be possible to run Qemu without Xorg (with either qemu's -curses or -nographics parameters) by redirecting stdin/stdout/stderr to another tty and then ``chvt`` to that tty programatically.
But, Qemu logs may get lost without Xorg, which are available when Qemu runs with Xorg. It continuously prints logs to the console it was launched with (tty1 here) and outputs the guest to the Xorg server. But, without Xorg, it only has one console to output to, which is then used to display the guest OS.
Also, there is a chance for confusion. Qemu wont work if the guest outputs Graphic data when curses mode is enabled. But, with X, it will work no matter what mode the guest is in.

**Comment by atrent** [comment]
Ok, leave it as a comment in source code so that we'll remember at least the option

Moreover (almost another issue), could it be useful to have a very lightweight wm? (such as i3)

**Comment by shreyanshk** [comment]
Note added 65e38ee34e2d96593262852d0466fc746a093111

It's possible to add a WM but the rootfs is very minimal. It's doubtful that any user would find it to be a productive environment any way. Also, if any WM is included, some configuration files will also need to be added. If added, most probably, no user is going to find included config useful (User profile config is a very personal thing, after all).

**Comment by atrent** [comment]
I agree, it was just a thought, maybe I'll create a custom image just for my experiments
