### ISSUE TITLE
aria2 parameters configurable

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#39]
it would be useful to have some configurability (at the yaml level) of the aria2 daemon running on the nodes, e.g., to change verbosity

**Comment by shreyanshk** [comment]
It should be taken care with #25.

**Comment by atrent** [comment]
better to close #25 (since we abandoned hefur) and continue with this issue then

**Comment by shreyanshk** [comment]
added parameter aria2.console_log_level in Boottorrent.yaml file to control Aria2 logging.
valid values: debug, info, notice, warn or error

**Comment by atrent** [comment]
should other aria2 parameters made be configurable?

**Comment by shreyanshk** [comment]
Some parameters may be useful:

* bt-max-peers
* max-upload-limit
* quiet

But, Aria2 is excellent at managing download speeds automatically and log level can be controlled by console_log_level parameter.

Full list of parameters of interest are:
* https://aria2.github.io/manual/en/html/aria2c.html#basic-options
* https://aria2.github.io/manual/en/html/aria2c.html#bittorrent-specific-options
* https://aria2.github.io/manual/en/html/aria2c.html#advanced-options

**Comment by atrent** [comment]
I'm closing this issue because at the moment the aria2 configurability is enough, we may re-open it in the future if needed.
