### ISSUE TITLE
bsdtar

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#4]
is there a reason to use bsdtar instead of the "standard" tar?

**Comment by shreyanshk** [comment]
The initrd requires a specific format (SVR4 with no CRC, newc format) and I quickly got bsdtar to generate it. So, haven't fiddled with standard tar.

**Comment by gbiscuolo** [comment]
Hi Shreyansh!

* Shreyansh Khajanchi [2018-06-12 05:30:47 -0700]:

>The initrd requires a specific format (SVR4 with no CRC, newc format) and I
>quickly got bsdtar to generate it. So, haven't fiddled with standard tar.

AFAIK the de-facto standard for Linux is to create an initramfs, there is a
tool named mkinitramfs in initramfs-tools-core/stable package: could you
please verify if you can replace bsdtar with mkinitramfs?

ciao
Giovanni

-- 
Giovanni Biscuolo
Xelera - IT infrastructures
http://xelera.eu/contact-us/

**per favore** Quota Bene: http://wiki.news.nic.it/QuotarBene
**please** use Inline Reply: https://en.wikipedia.org/wiki/Posting_style#Interleaved_style

**Comment by shreyanshk** [comment]
I think I wasn't clear on usage of bsdtar.
I have tried to clarify the usage of bsdtar and the rationale of implementation here: https://boottorrent.readthedocs.io/en/latest/internals.html#bsdtar
Please consider reading it.
Please let me know if you have other recommendation.

Additionally, I can replace bsdtar with GNU's cpio.

**Comment by gbiscuolo** [comment]
Ciao,

* Shreyansh Khajanchi [2018-06-17 01:09:10 -0700]:

>I have tried to clarify the usage of bsdtar and the rationale of
>implementation here:
>https://boottorrent.readthedocs.io/en/latest/internals.html#bsdtar
>Please consider reading it.

I read it:

3. mkinitcpio/mkinitramfs etc
    | Needs extra configuration files to work that is avoidable on other approaches.
    | Are geared towards creation of full initrd images. We only need to pack a folder.

and simply I do not agree with your choiche of bsdtar vs mkinitramfs based on
this considerations :-)

as low-pri for this GSoC you could consider giving mkinitrd a try (DIET
milestone), but this is your project so I'm not going to insist, and please
Andrea Trentini do not insist too :-)

>Please let me know if you have other recommendation.

no other recommendation

should you close this issue as "won't fix"?

ciao
Giovanni

-- 
Giovanni Biscuolo
Xelera - IT infrastructures
http://xelera.eu/contact-us/

**per favore** Quota Bene: http://wiki.news.nic.it/QuotarBene
**please** use Inline Reply: https://en.wikipedia.org/wiki/Posting_style#Interleaved_style

**Comment by shreyanshk** [comment]
Hi,
Please note that initramfs-tools-core's mkinitramfs pulls a dependency on GNU cpio (and, As I've noted in the documentations, GNU cpio can replace bsdtar) (https://packages.debian.org/stretch/initramfs-tools-core).
Also, mkinitcpio pulls a dependency on bsdtar in libarchive (https://www.archlinux.org/packages/core/any/mkinitcpio/).
And mostly distributions either have mkinitcpio or initramfs-tools or distribution's own equivalent and only one of these. Depending on initrd tools means the project is locked to distros with same tools.

Now, BootTorrent (during runtime) is only packing client data (out/torrents directory) in a small archive (~5 KB for every torrent) to be mounted by SliTaz kernel during boot. It is not packing a complete initrd.
