### ISSUE TITLE
dafault values in config files for missing variables?

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#41]
I don't know if it would be useful or misleading for the user, how about setting default values for variables in config files (yaml)? I mean: implementing a hard-coded default value if the variable is not found in the yaml.

It happened to me that I upgraded boottorrent but left Boottorrent.yaml at previous version (without console_log_level for aria2) and I got an error.
Is it better getting an error or a default value?

**Comment by shreyanshk** [comment]
> how about setting default values for variables in config files

The skeleton config file is updated with all changes (unless, I happen to forget it, of course). I push updated default values when relevant changes are made.

> don't know if it would be useful or misleading for the user

Default values or errors are two ways to handle it and, I think, neither one of them is more correct than others.
Implicit default values may make it easier to use but at the cost of comparatively harder debugging for the user in case of errors. (Users need to account for "magic" that is happening in the code now)
Errors make the logic more transparent and debugging easier but may have slight learning associated with fixing them.

> Is it better getting an error or a default value?

The reasoning is that users of this project are going to be "power" users.
Normal people don't go around finding out ways to boot computers as supported by BootTorrent.
If provided with informational/actionable error messages, generally, 'power' users can find their way.
So, in this instance, I believe, error messages are more useful.
But I'm open to other considerations.

**Comment by atrent** [comment]
I agree with error messages, I'm closing the issue
