### ISSUE TITLE
tried "-accel=kvm" but it only shows a "_" cursor

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#42]
(moreover other consoles are no longer reachable, I have to switch off and then on again the machine)

how can I debug it?

**Comment by atrent** [comment]
the correct option is "-enable-kvm", same result (the machines are still pingable)

**Comment by shreyanshk** [comment]
> (moreover other consoles are no longer reachable, I have to switch off and then on again the machine)

This is related to #38 
The machine IO/Network seems to work but display is completely unavailable.

**Comment by atrent** [comment]
actually I switched to a console of alpine (since it's not booting) and tried to launch qemu at prompt, the problem is "could not access KVM kernel module"

**Comment by shreyanshk** [comment]
> actually I switched to a console of alpine

So display is working. meaning this is not related to #38 , right?

> could not access KVM kernel module

KVM modules are in different package in SliTaz. (linux-kvm)
It's possible to include them but the image will be bigger.

**Comment by atrent** [comment]
1) yes, not related to #38
2) how bigger? I think it would be very useful to make kvm available

**Comment by shreyanshk** [comment]
The image with KVM was only a megabyte bigger.
Please test the new ``kvm`` branch with the new rootfs.
It includes another slitaz package ``linux-kvm``.

**Comment by shreyanshk** [comment]
PS: I'm removing ``kvm`` branch. The package (linux-kvm) has been committed to ``dev`` branch.
Please check if KVM is working for you.

**Comment by atrent** [comment]
very strange, kvm still does not work and now X works on one machine only (of the two I'm using)
![2018-07-07_22 57 00](https://user-images.githubusercontent.com/412584/42414723-b9328096-823b-11e8-9ef0-5a7bfe8db073.jpg)
![2018-07-07_22 56 52](https://user-images.githubusercontent.com/412584/42414724-b956b06a-823b-11e8-95ac-e488d21099a1.jpg)

**Comment by atrent** [comment]
I'd like to try and build a slitaz image, would you provide a dockerrfile for building? (it was mentioned in planning and in emails we exchnaged)

maybe it's just that xorg-video-all should be included in slitaz

**Comment by shreyanshk** [comment]
Docker is not used to build the slitaz image.
So, a docker file is not there. (I'm using vbox) 
But, I think you could use docker image slitaz/slitaz-base to get a slitaz system.
``docker pull slitaz/slitaz-base`` and ``docker run -it slitaz/slitaz-base``
And you could use ``docker cp`` to copy files to-and-fro from the system.
The build process should remains the same even in docker containers.

**Comment by atrent** [comment]
I'm trying tazlito, what flavor did you start with?

**Comment by shreyanshk** [comment]
LiveCD rolling
http://www.slitaz.org/en/get/

**Comment by atrent** [comment]
I know, but when you rebuild the image, from what flavor do you start from?

**Comment by shreyanshk** [comment]
> I know, but when you rebuild the image, from what flavor do you start from?

I'm unable to follow.
I am not taking any extra steps...... I just copy the folder (``phase1bootstrap/slitaz``) and CD into it.
then I run ``sudo tazlito gen-distro``.

**Comment by atrent** [comment]
tazlito is a program available in the slitaz distro, you must boot into it to have it available
I boot into slitaz (from qemu) and the follow the instructions you referred in the faq (https://boottorrent.readthedocs.io/en/latest/faq.html#i-have-exotic-hardware-and-boottorrent-doesn-t-include-it-s-software-what-can-i-do-to-make-it-work), i.e., http://doc.slitaz.org/en:handbook:hacklivecd

**Comment by shreyanshk** [comment]
That is correct.
I mean, I've installed slitaz into a vm with slitaz-rolling.iso and Tazlito is already included in it. 
And then I attach a flash drive to the vm to copy files.
