### ISSUE TITLE
rename envtest/Boottorrent.yaml

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#44]
since it's an example I would rename it to Boottorrent.yaml.example

so that, once configured a local Boottorrent.yaml, every time a user 'git pull's the repo for updates git would not complain

**Comment by shreyanshk** [comment]
I've renamed the file to ``Boottorrent.yaml.example``.
I've also added the original file ``Boottorrent.yaml`` to ``.gitignore``.
So, git status should also report a clean working directory.
