### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#6]
$ pip install -e boottorrent
Directory 'boottorrent' is not installable. File 'setup.py' not found.

**Comment by shreyanshk** [comment]
Maybe the download was corrupt. I mean, there is a setup.py file in the project root.
Check here: https://github.com/shreyanshk/boottorrent/blob/dev/setup.py
Please consider retrying.

**Comment by atrent** [comment]
there is no dir 'blob'

**Comment by atrent** [comment]
(btw I'm following the guide in the README, step by step)

**Comment by shreyanshk** [comment]
> there is no dir 'blob'
It's GitHub's url pattern.
files in any repo are accessible via repo_url/blob/file_path

**Comment by shreyanshk** [comment]
Okay, I am unable to follow up. I think there is some sort of confusion.

Just to be double sure, few moments ago, I tried to install the package on clean, unused computer (In fact, I installed Py3.6 on spot) and it worked.

`ubuntu@ip-172-31-24-45:~$ virtualenv -p python3.6 venv
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /home/ubuntu/venv/bin/python3.6
Also creating executable in /home/ubuntu/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
ubuntu@ip-172-31-24-45:~$ cd venv
ubuntu@ip-172-31-24-45:~/venv$ source bin/activate
(venv) ubuntu@ip-172-31-24-45:~/venv$ git clone https://github.com/shreyanshk/boottorrent
Cloning into 'boottorrent'...
remote: Counting objects: 369, done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 369 (delta 31), reused 51 (delta 16), pack-reused 299
Receiving objects: 100% (369/369), 50.74 MiB | 31.97 MiB/s, done.
Resolving deltas: 100% (164/164), done.
Checking connectivity... done.
(venv) ubuntu@ip-172-31-24-45:~/venv$ pip install -e boottorrent
Obtaining file:///home/ubuntu/venv/boottorrent
Collecting Click>=6.0 (from boottorrent==0.1.0)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting PyYAML>=3.12 (from boottorrent==0.1.0)
Collecting Jinja2>=2.10 (from boottorrent==0.1.0)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting requests>=2.18.4 (from boottorrent==0.1.0)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->boottorrent==0.1.0)
Collecting certifi>=2017.4.17 (from requests>=2.18.4->boottorrent==0.1.0)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.18.4->boottorrent==0.1.0)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.18.4->boottorrent==0.1.0)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.18.4->boottorrent==0.1.0)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Installing collected packages: Click, PyYAML, MarkupSafe, Jinja2, certifi, chardet, idna, urllib3, requests, boottorrent
  Running setup.py develop for boottorrent
Successfully installed Click-6.7 Jinja2-2.10 MarkupSafe-1.0 PyYAML-3.12 boottorrent certifi-2018.4.16 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
(venv) ubuntu@ip-172-31-24-45:~/venv$ 
`

Also, I'm trying to show you that such a file exists (note: /blog/ is GitHub's URL slug, and like I said, it's there for every repository) and not asking you to download anything.

I'm trying be clear and precise. Please pardon me if I came across as rude.

**Comment by atrent** [comment]
you did not document the use of virtualenv

**Comment by shreyanshk** [comment]
> you did not document the use of virtualenv!

Please understand virtualenv was only used because that computer didn't default to Python3.6
The command should work regardless of virtualenv was installed or not.
The same command installs the package:
* inside the virtualenv, only usable in the virtualenv, if it is activated
* to the user directory (~) if without virtualenv
* as a global system package, if given access to root filesystem

**Comment by atrent** [comment]
you should still document it

**Comment by shreyanshk** [comment]
> you should still document it

As you know there are many ways to install packages for lots of different situations.
Documenting for each and every package manager (which includes: pipenv, easy_install, pip, anaconda ... etc; some distros even use their package managers to manage python packages!) and their various modes quickly becomes the task of documenting the platform infrastructure instead.
I think it's reasonable to state a method that works universally on all platforms.
If a user chooses different tools, it's reasonable to expect them to know how to work with their chosen set of tools.
What do you think?

**Comment by atrent** [comment]
you don't need to explain in detail, you may refer to the (virtualenv/etc.) documentation, but at least you should mention the problem (of not having Python3.6 as a default), not everybody (especially me! I'm not fond of Python as I told you) is deeply knowledgeable of the quirks...

**Comment by shreyanshk** [comment]
I've updated the readme file in commit 7810d2fdf0650a2b3764024836d53ddda08dc6de .
Also suggested alternatives as well.
