### ISSUE TITLE
general note for the README file

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#8]
[from now on I'll also use issues to track notes/comments I make in various files, so that we can track down the process more easily and transparently]

The README is way better now!

The next thing to do is to summarize there (as an introduction) the different "usecases" (contexts&actors) so that a "would be" user may identify if and how this project can be of use for him

At the moment it's still not clear (i.e., not documented) the role of the 'boottorrent' executable (.py), I understand (but I had to read the source code!) that it's a "launcher" of various components (e.g., the dnsmasq), it must be stated and documented in detail. See also #7

**Comment by shreyanshk** [comment]
I've summarized the use cases on the project introduction page.
I've also documented the role of boottorrent executable in the Usage guide.
https://boottorrent.readthedocs.io/en/latest/usage.html

**Comment by atrent** [comment]
(commented the architecture file)

**Comment by shreyanshk** [comment]
Use cases and documentation about the launcher is there now.
Let me know if there are any other issues.
