### ISSUE TITLE
images in the README

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#9]
maybe linking to the graph on this (http://sl-lab.it/dokuwiki/doku.php/tesi:boottorrent_en#graphs) section of the original thesis would be even more explicative

**Comment by shreyanshk** [comment]
Consider sending English translated images.

**Comment by atrent** [comment]
done http://sl-lab.it/dokuwiki/doku.php/tesi:boottorrent_en#performance_graphs

**Comment by atrent** [comment]
please cite the source of images and explain that these are not your results but the original work results
